### ISSUE TITLE
[Question] Fork or external contributor rights ?

### ISSUE THREAD

**Issue by mickaelandrieu** [Lp-digital/github-event-parser#19]
Hi,
as you know, I used to be the main/(only?) contributor to this package.

What do you prefer ? Keep this one maintained (giving me rights to admin it) or should I start a fork ?

ping @crouillon

**Comment by mickaelandrieu** [comment]
Ping @crouillon,  please tell me :)

**Comment by crouillon** [comment]
Hello @mickaelandrieu, you have admin rights on this repositories by now.

**Comment by mickaelandrieu** [comment]
Thank you :)
