### ISSUE TITLE
Push event can't be resolved

### ISSUE THREAD

**Issue by martinssipenko** [Lp-digital/github-event-parser#44]
The implementation to resolve `Push` event does not align with the payload.

According to GitHub's documentation the Push event has different payload than the Push event from WebHook API. https://developer.github.com/v3/activity/events/types/#pushevent

What would be the possible solutions to tackle this issue? I'm happy to send a Pull Request, but before I do that, I want to align with maintainers of this project.

**Comment by mickaelandrieu** [comment]
Hello, the aim of this library is to be totally aligned with the GitHub API, go for it :)

Thank you for your pull request!

Mickaël

**Comment by martinssipenko** [comment]
Ok, so should I change the existing PullEvent? This will break the backwards compatibility.

Another option would be to have a different class for `WebhookPush` event..

What do you think?

**Comment by mickaelandrieu** [comment]
As we are not yet in 1.0, I'm in favor of an update of existing event 👍

**Comment by mickaelandrieu** [comment]
Any news about it?

**Comment by martinssipenko** [comment]
Have not got this far yet, once I'll need to use the `Push` event, I'll have to do it, unless someone else beats me to it.
