### ISSUE TITLE
[RFC] events without repository payload

### ISSUE THREAD

**Issue by acrobat** [Lp-digital/github-event-parser#45]
I'm using the library with the new integrations api and for integrations there are a few new events. See [integration event docs](https://developer.github.com/early-access/integrations/webhooks/#integration-webhook-events). I would like to add these events and also the other missing types.

But all events extend from the `AbstractEventType` class, in this class it is expected that each event has a repository in it's payload. But these events and a few other V3 api events also lack the repository as the event is not linked to a repository (TeamEvent, OrganizationEvent)

So what I would propose is we split this class and move the repository assignment to a `RepositoryAwareEventType` class, which will extend from `AbstractEventType`. This way we can use the `AbstractEventType` as a base for all events without a repository payload and have all other events extend from `RepositoryAwareEventType`.

@mickaelandrieu What do you think about this approach?

**Comment by mickaelandrieu** [comment]
Hello @acrobat,

yes, make sense!

Go for a pull request, as soon as it's covered by tests, this will be merged.

Mickaël

**Comment by acrobat** [comment]
Great! Thanks for the quick feedback!
