### ISSUE TITLE
[RFC] Make entities immutable

### ISSUE THREAD

**Issue by acrobat** [Lp-digital/github-event-parser#49]
Not a big issue but something that looks a bit weird to me. Some of the entity classes have setters which is, in my opinion, not right. The github event determines the content of the class (what is done in the constructor). So the setters should not be available as you let the users modify the event data. That's why I propose to remove the setters from the entity classes and have private properties with getters to access the data.

If users want to changes the data of the entity they need to pre process the data, before feeding it to the parser.

What do you think @mickaelandrieu?

**Comment by mickaelandrieu** [comment]
My very old first version was only about immutable entities, I don't remember why I've added setters and to be honest I don't think getters have sense when I could use [__get()](http://php.net/manual/fr/language.oop5.overloading.php#object.get) to do the same and remove almost 90% of the code.

Need to think about it, this is why I don't want to flag a major version right now :)

**Comment by acrobat** [comment]
Yeah the biggest issue would indeed be code completion and maybe that the code would be more clear we you have specific getters.

I understand :) Take your time and when you have a decision about this, just ping me!

**Comment by mickaelandrieu** [comment]
Ok, I've removed all setters.

If someone need it, he'll explain why. I think abuse the ``_get()`` here is a bad idea: PHP still don't provide automatic getters like in C#, this is sad but we'll live with it, right? :)

Thanks for the issue :)

**Comment by acrobat** [comment]
:+1: Thanks @mickaelandrieu
