### ISSUE TITLE
Does this library handle follow event? 

### ISSUE THREAD

**Issue by samayo** [Lp-digital/github-event-parser#51]
If I am not mistaken, currently github does not trigger events when a user follows another: https://developer.github.com/v3/activity/events/types/#followevent 

Not sure if I am mistaken, if not then does you library handle/send follow events?

**Comment by mickaelandrieu** [comment]
Hello @samayo,
as GitHub doesn't send Follow events anymore it's impossible to handle them.

Mickaël

**Comment by samayo** [comment]
Ah, too bad! 

Thanks anyway.
